baseURL = "https://xiupos.net/"
defaultContentLanguage = "ja"
title = "Xiupos"
theme = "m10c"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "ABOUT"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "TAGS"
    url = "/tags/"
    weight = 2

[params]
  displayTitle = "XiupoÏ‚"
  author = "xiupos"
  description = "Tech notes, trip photos, etc."
  menu_item_separator = " / "
  blogTitle = "Xiupoy blog"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/xiupos"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/xiupos"
  [[params.social]]
    icon = "message-square"
    name = "Misskey"
    url = "https://m.x4s.io/@xiupos"
  [params.style]
    darkestColor = "#171817"
    darkColor = "#101110"
    primaryColor = "#61ae76"
    lightColor = "#DCDDDD"
    lightestColor = "#EDEDEB"
